title: [Da'Shayne's Portfolio of Cybersecurity Projects]
description:[A collection of cybersecurity projects showcasing log analysis, attack detection, and incident investigation skills for SOC and InfoSec roles.]
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
